"use client";

import "./admin.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { useEffect } from "react";

{
  /**
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/
}

export default function RootLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
